import React, { useEffect, useState } from "react";
import { Flex } from "@chakra-ui/react";
import { TimerCounter, ActionButtons } from "@/components/timer";
import Head from "next/head";
import SelectContainer from "./SelectContainer";

export interface TimerOption {
  label: string;
  value: number;
}

export interface Time {
  hour: number;
  min: number;
  sec: number;
}

function Timer() {
  const [isRunning, setIsRunning] = useState<boolean>(false);
  const [isPaused, setIsPaused] = useState<boolean>(false);
  const [time, setTime] = useState<Time>({
    hour: 0,
    min: 0,
    sec: 0,
  });

  useEffect(() => {
    const intervalId = setInterval(() => {
      setTime((prevTime) => {
        if (!isRunning || isPaused) {
          clearInterval(intervalId);
          return prevTime;
        }
        let { hour, min, sec } = prevTime;

        if (sec === 0) {
          if (min === 0) {
            if (hour === 0) {
              clearInterval(intervalId);
              return prevTime;
            }
            hour -= 1;
            min = 59;
            sec = 59;
          } else {
            min -= 1;
            sec = 59;
          }
        } else {
          sec -= 1;
        }

        return {
          hour,
          min,
          sec,
        };
      });
    }, 1000);

    return () => clearInterval(intervalId);
  }, [isPaused, isRunning, time]);

  return (
    <>
      <Head>
        <title>
          {isRunning
            ? `${time.hour}:${time.min}:${time.sec}`
            : "타이머 - 코테 준비 타이머"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex display="flex" alignItems="center" h="85px" gap="10px" m="0 auto">
        {isRunning ? (
          <TimerCounter time={time} />
        ) : (
          <SelectContainer time={time} setTime={setTime} />
        )}
      </Flex>
      <ActionButtons
        isRunning={isRunning}
        setIsRunning={setIsRunning}
        isPaused={isPaused}
        setIsPaused={setIsPaused}
      />
    </>
  );
}

export default Timer;
